### ISSUE TITLE
When clicking Upgrade option to any pricing results in 500 error

### ISSUE THREAD

**Issue by chapimenge3** [Kinfe123/MegaMess#36]
![image](https://github.com/Kinfe123/MegaMess/assets/48279189/e61768b6-fec5-4511-a6b8-f291b582732f)

Steps:

1. Login and head over to pricing page
2. Try clicking upgrade 
3. You will see Error Page and the console page shows the above screenshot

**Comment by Kinfe123** [comment]
Well, Thanks chapi for the issue. i will try providing a fix when possible.
